### ISSUE TITLE
No structures. Is there any way to automatically add structures?

### ISSUE THREAD

**Issue by dberga** [SnakeManPMC/arma-3-terrain-builder-TemplateLibs#1]
A way would be to localize the color / shape / size of the building, select an asset for that structure and add the specific asset on these coordinates. Is that even possible?

Here is the example of Kyiv, some objects like Trees and so on have been added, but not structures. So all the terrain appears flat. Is that a loading error or is that feature not yet enabled?
![image](https://github.com/SnakeManPMC/arma-3-terrain-builder-TemplateLibs/assets/6095883/db2e9556-cf8c-473a-a750-dc76a8872202)

**Comment by SnakeManPMC** [comment]
This is github repository for [PMC ArmA 3 Terrain Builder Template Libraries (TemplateLibs)](https://pmc.editing.wiki/doku.php?id=arma3:terrain:terrain-builder-templatelibs). If you want to discuss about PMC terrains, head over to [PMC Tactical forum](https://www.pmctactical.org/forum/) and post there.
